{% set name = "pandas_schema" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6bfc52c4bae9cdd7420fbe8c4b0622b769457827c3fc819928405638caf605f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python  >3
  run:
    - numpy
    - pandas
    - python  >3

test:
  imports:
    - pandas_schema

about:
  home: https://github.com/TMiguelT/PandasSchema
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: A validation library for Pandas data frames using user-friendly schemas

extra:
  recipe-maintainers:
    - foellmelanie
